name:                marketsim
version:             0.1.0.0
github:              "SupremeSource/marketsim"
license:             BSD3
author:              "Supreme Source"
maintainer:          "zimulajan0@gmail.com"
copyright:           "2023 Supreme Source"


extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/githubuser/marketsim#readme>

dependencies:
- base >= 4.7 && < 5
- random
- scotty
- bytestring
- time
- text
- containers
- parallel
- process
- aeson
- deriving-aeson
- aeson-pretty
- QuickCheck
- hspec
- ghci-dap
- haskell-dap
- random-shuffle
- hspec-expectations

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: 
    - src
    - app
    - Settings
    - property-test
  
  exposed-modules: 
   - Lib
   - InputOutput
   - Util
   - Statistics
   - Filepaths
   - RunSettings
   - DataTypes
   - Colours
   - Generator
   - PosCycle
   - Tests
  default-extensions:
   - ImportQualifiedPost
   - InstanceSigs
   - ScopedTypeVariables

executables:
  marketsim-exe:
    main:  Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - marketsim
    - scotty
    - bytestring
    - random
    - time
    - text
    - containers
    - parallel
    - process
    - aeson
    - deriving-aeson
    - aeson-pretty
    - QuickCheck
    - hspec
    - ghci-dap
    - haskell-dap
    - random-shuffle
    - hspec-expectations
   
  marketsim-server-exe:
    main:  Main.hs
    source-dirs: Server
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - marketsim
    
# Comment out the tests section if you don't have test directory or modules.
tests:
  marketsim-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - marketsim
    - hspec
    - QuickCheck