name:                marketsim
version:             0.1.0.0
github:              "SupremeSource/marketsim"
license:             BSD3
author:              "Supreme Source"
maintainer:          "zimulajan0@gmail.com"
copyright:           "2023 Supreme Source"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/githubuser/marketsim#readme>

dependencies:
- base >= 4.7 && < 5
- random
- scotty
- bytestring
- time
- text
- containers
- parallel
- process
- aeson
- deriving-aeson
- aeson-pretty
- random-shuffle

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: 
    - src
    - app
    - Settings
  
  exposed-modules: 
   - Lib
   - InputOutput
   - Util
   - Statistics
   - Filepaths
   - RunSettings
   - DataTypes
   - Colours
  default-extensions:
   - ImportQualifiedPost
   - InstanceSigs
   - ScopedTypeVariables

executables:
  marketsim-exe:
    main:  Main.hs
    source-dirs:  app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - marketsim
    - scotty
    - bytestring
    - random
    - time
    - text
    - containers
    - parallel
    - process
    - aeson
    - deriving-aeson
    - aeson-pretty
    - random-shuffle
    

# Comment out the tests section if you don't have test directory or modules.
# tests:
#   marketsim-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - marketsim
